#!/usr/bin/env bash
# Install and configure HAproxy Load Balancer (High Avaialbility Proxy)

# Update apt packages and Install haproxy
sudo apt -y update
sudo apt install -y haproxy

# Change file mode of /etc/haproxy/haproxy.cfg to 777 to alter its contents

sudo chmod 777 /etc/haproxy/haproxy.cfg
printf %s "
listen hbnb
        bind 0.0.0.0:80
        mode http
        stats enable
        stats uri /haproxy?stats
        balance roundrobin
        option httpclose
        option forwardfor
        server 343420-web-01 18.206.197.137:80 check
        server 343420-web-02 52.201.187.201:80 check
" >> /etc/haproxy/haproxy.cfg
sudo chmod 644 /etc/haproxy/haproxy.cfg

# Restart haproxy
sudo service haproxy start
