#!/usr/bin/env bash
#list dir without no.
for file in *; do
    # Check if the file is not a hidden file
    if [[ $file != .* ]]; then
        # Extract the part of the name after the first dash
        name_part=$(echo "$file" | cut -d'-' -f2-)
        echo "$name_part"
    fi
done
