#!/usr/bin/env bash
# Enable IP forwarding
sudo sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/' /etc/ufw/sysctl.conf

# Allow traffic on port 8080/TCP
sudo ufw allow 8080/tcp

# Add port forwarding rule
sudo bash -c 'echo "iptables -t nat -A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80" >> /etc/ufw/before.rules'

# Reload UFW to apply changes
sudo ufw reload
